language: ruby
cache: bundler
rvm:
  - 2.1.5
  - ruby-head
  - jruby-head
  - rbx-2.5.3
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.5.3
script:
  - bundle exec rspec
before_install: gem update bundler
